### ISSUE TITLE
Publication link?

### ISSUE THREAD

**Issue by usuyama** [ExaNLP/sket#1]
Hi @stefano-marchesin @OrnellaIrrera

Are there papers describing or using SKET?

**Comment by stefano-marchesin** [comment]
Hi @usuyama,

Thanks for your interest in SKET! 

We have published a paper where we use SKET on Nature npj Digital Medicine, here is the link to the paper (open access): https://www.nature.com/articles/s41746-022-00635-4

On the other hand, we have submitted another paper only focusing on SKET and its functionalities, but it's not published yet. 

At the moment, if you want to cite or read about the tool, you can refer to the npj digital medicine paper.

Cheers,
Stefano
