### ISSUE TITLE
ValueError: [E966] `nlp.add_pipe` now takes the string name of the registered component factory,

### ISSUE THREAD

**Issue by nabilapuspit** [ExaNLP/sket#2]
Hi, I just try your code using en_core_sci_sm spacy model and example text just like the instruction that you've provided, but I got this error 
ValueError: [E966] `nlp.add_pipe` now takes the string name of the registered component factory, not a callable component. Expected string, but got <bound method NERD.expand_entity_mentions of <sket.nerd.nerd.NERD object at 0x7f2e23afc160>> (name: 'expand_entities').
I've search it on internet and they say "For spaCy v3, you just want to add it with its string name and skip instantiating the class separately" but I still got confused, can you tell me what to do?

**Comment by nabilapuspit** [comment]
Hi, I just found out that this problem happen because of my stupidity. I just found that Spacy had upgrade their version to v3, and it has a mayor difference on the code, so in order to run this program, you have to downgrade your Spacy version into v2. basically just follow the requirements.txt lol.

After the program compailed perfectly, you'll have 3 outputs : concepts, graphs, and labels. can you tell me what is the concepts and graphs function in this if you only use the labels for the MIL?

**Comment by stefano-marchesin** [comment]
Hi, thanks for the interest in our work.

Concepts and graphs are not used in the MIL work published on npj Digital Medicine. However, we have another paper submitted that showcases all the different SKET applications. In few words, concepts and graphs can be used for knowledge representation, report summarization, knowledge discovery/visualization, etc. SKET works at different knowledge levels and can be integrated within different pipelines depending on the downstream applications and needs.

Hope it helps!

Cheers,
Stefano
