### ISSUE TITLE
SKET X login

### ISSUE THREAD

**Issue by usuyama** [ExaNLP/sket#3]
I wanted to check out SKET X demo, but the server from paper requires username and password. Is there a demo version that we can try?

> SKET X is available at http://[w3id.org/sketx](http://w3id.org/sketx)[1]
https://www.sciencedirect.com/science/article/pii/S2153353922007337#fn0005

**Comment by stefano-marchesin** [comment]
Hi @usuyama,

Sorry for the late reply. The demo version of SKET X can be accessed using the following credentials

Username: demo
Password: demo

Let me know if you have any other issues with that.

Cheers,
Stefano

**Comment by usuyama** [comment]
The username/password worked for me. Very impressive demo! Thank you, @stefano-marchesin
